parameters:

    ccdn_user_security.session.repository.class:                                      CCDNUser\SecurityBundle\Repository\SessionRepository

    ccdn_user_security.gateway.session.class:                                         CCDNUser\SecurityBundle\Gateway\SessionGateway
    ccdn_user_security.manager.session.class:                                         CCDNUser\SecurityBundle\Manager\SessionManager

    ccdn_user_security.component.authentication.handler.login_failure_handler.class:  CCDNUser\SecurityBundle\Component\Authentication\Handler\LoginFailureHandler
    ccdn_user_security.component.authentication.handler.login_success_handler.class:  CCDNUser\SecurityBundle\Component\Authentication\Handler\LoginSuccessHandler
    ccdn_user_security.component.authentication.handler.logout_success_handler.class: CCDNUser\SecurityBundle\Component\Authentication\Handler\LogoutSuccessHandler

    ccdn_user_security.component.route_referer_ignore.chain.class:                    CCDNUser\SecurityBundle\Component\Listener\Chain\RouteRefererIgnoreChain
    ccdn_user_security.component.listener.route_referer_listener.class:               CCDNUser\SecurityBundle\Component\Listener\RouteRefererListener
    ccdn_user_security.component.listener.blocking_login_listener.class:              CCDNUser\SecurityBundle\Component\Listener\BlockingLoginListener
    ccdn_user_security.component.authorisation.voter.client_login_voter.class:        CCDNUser\SecurityBundle\Component\Authorisation\Voter\ClientLoginVoter
    ccdn_user_security.component.authentication.tracker.login_failure_tracker.class:  CCDNUser\SecurityBundle\Component\Authentication\Tracker\LoginFailureTracker

services:

    #
    # Repositories.
    #
    ccdn_user_security.session.repository:
        class: %ccdn_user_security.session.repository.class%
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - 'CCDNUser\SecurityBundle\Entity\Session'

    #
    # Gateways.
    #
    ccdn_user_security.gateway.session:
        class: %ccdn_user_security.gateway.session.class%
        arguments:
            - @doctrine

    #
    # Managers.
    #
    ccdn_user_security.manager.session:
        class: %ccdn_user_security.manager.session.class%
        arguments: 
            - @doctrine
            - @ccdn_user_security.gateway.session

    #
    # Login/Logout Success/Failure Handlers.
    #
    ccdn_user_security.component.authentication.handler.login_failure_handler:
        class: %ccdn_user_security.component.authentication.handler.login_failure_handler.class%
        arguments:
            - @router
            - @ccdn_user_security.component.authentication.tracker.login_failure_tracker
            - %ccdn_user_security.login_shield.enable_shield%
            - %ccdn_user_security.login_shield.primary_login_route.name%
            - %ccdn_user_security.login_shield.primary_login_route.params%
        tags:
            - { name: 'monolog.logger', channel: 'security' }

    ccdn_user_security.component.authentication.handler.login_success_handler:
        class: %ccdn_user_security.component.authentication.handler.login_success_handler.class%
        arguments: []
        tags:
            - { name: 'monolog.logger', channel: 'security' }

    ccdn_user_security.component.authentication.handler.logout_success_handler:
        class: %ccdn_user_security.component.authentication.handler.logout_success_handler.class%
        arguments: []
        tags:
            - { name: 'monolog.logger', channel: 'security' }

    #
    # Referer Listener.
    #
    ccdn_user_security.component.route_referer_ignore.chain:
        class: %ccdn_user_security.component.route_referer_ignore.chain.class%

    ccdn_user_security.component.listener.route_referer_listener:
        class: %ccdn_user_security.component.listener.route_referer_listener.class%
        arguments:
            - @router
            - @ccdn_user_security.component.route_referer_ignore.chain
            - %ccdn_user_security.route_referer.route_ignore_list%
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    ccdn_user_security.component.listener.blocking_login_listener:
        class: %ccdn_user_security.component.listener.blocking_login_listener.class%
        arguments:
            - @router
            - @ccdn_user_security.component.authentication.tracker.login_failure_tracker
            - %ccdn_user_security.login_shield.enable_shield%
            - %ccdn_user_security.login_shield.block_routes_when_denied%
            - %ccdn_user_security.login_shield.block_for_minutes%
            - %ccdn_user_security.login_shield.limit_failed_login_attempts.before_recover_account%
            - %ccdn_user_security.login_shield.limit_failed_login_attempts.before_return_http_500%
            - %ccdn_user_security.login_shield.recover_account_route.name%
            - %ccdn_user_security.login_shield.recover_account_route.params%
            - %ccdn_user_security.login_shield.primary_login_route.name%
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    #
    # Authorisation Voter
    #
    ccdn_user_security.component.authorisation.voter.client_login_voter:
        class: %ccdn_user_security.component.authorisation.voter.client_login_voter.class%
        arguments:
            - @service_container # for getting Request service
            - @ccdn_user_security.component.authentication.tracker.login_failure_tracker
            - %ccdn_user_security.login_shield.enable_shield%
            - %ccdn_user_security.login_shield.block_routes_when_denied%
            - %ccdn_user_security.login_shield.block_for_minutes%
            - %ccdn_user_security.login_shield.limit_failed_login_attempts.before_return_http_500%
        tags:
            - { name: security.voter }

    ccdn_user_security.component.authentication.tracker.login_failure_tracker:
        class: %ccdn_user_security.component.authentication.tracker.login_failure_tracker.class%
        arguments:
            - @ccdn_user_security.manager.session
            - %ccdn_user_security.login_shield.block_for_minutes%
