parameters:

    # Service Parameters defined in app/config

services:

    #
    # Repositories.
    #
    ccdn_user_security.repository.session:
        class: %ccdn_user_security.repository.session.class%
        arguments:
            - @ccdn_user_security.gateway.session
